"""Realistic mock Claude / OpenAI outputs, used when USE_MOCK_AI=true so the
full UI can be exercised without spending API credits (spec section 42).

The mock still reads the real deterministic bundle, so numbers shown in the
UI stay consistent with whatever dataset was actually uploaded.
"""
from __future__ import annotations

from app.models.schemas import (
    AIAnalysisResult,
    FullAnalysisBundle,
    ManagementRecommendation,
    TopDriverInsight,
)
from app.utils.formatting import format_currency_mnt, format_percent


def mock_claude_analysis(bundle: FullAnalysisBundle) -> AIAnalysisResult:
    k = bundle.kpis
    top_drivers_ranked = bundle.driver_ranking[:5] or []

    top_drivers = [
        TopDriverInsight(
            rank=i + 1,
            driver=d.driver,
            direction=d.direction,
            business_impact=(
                f"'{d.driver}' shows a {d.direction.replace('_', ' ')} relationship with net sales "
                f"(importance score {d.importance_score:.0f}/100)."
            ),
            evidence="; ".join(d.evidence) if d.evidence else "See driver_ranking evidence.",
            confidence=d.confidence,
        )
        for i, d in enumerate(top_drivers_ranked)
    ]

    top_channel = bundle.channel_analysis[0] if bundle.channel_analysis else None
    top_brand = bundle.brand_analysis[0] if bundle.brand_analysis else None

    return AIAnalysisResult(
        executive_summary=(
            f"[MOCK AI] Net sales totaled {format_currency_mnt(k.net_sales)} with a gross margin of "
            f"{format_percent(k.gross_margin_pct)}. Returns represented {format_percent(k.return_rate_pct)} "
            f"of units sold, and average discount was {format_percent(k.avg_discount_pct)}. This is a "
            f"mock analysis generated locally (USE_MOCK_AI=true) so the dashboard can be reviewed without "
            f"calling the Anthropic API."
        ),
        performance_overview=(
            f"Gross sales reached {format_currency_mnt(k.gross_sales)} against {format_currency_mnt(k.cogs)} "
            f"of cost of goods sold, producing gross profit of {format_currency_mnt(k.gross_profit)}."
        ),
        top_drivers=top_drivers,
        channel_insights=(
            [
                f"'{top_channel.group}' is the leading channel with {format_percent(top_channel.share_of_sales_pct)} "
                f"of net sales and {format_percent(top_channel.gross_margin_pct)} gross margin."
            ]
            if top_channel
            else ["No channel-level data available in this dataset."]
        ),
        brand_product_insights=(
            [f"'{top_brand.group}' is the top brand by net sales ({format_currency_mnt(top_brand.net_sales)})."]
            if top_brand
            else ["No brand-level data available in this dataset."]
        ),
        pricing_discount_insights=[
            f"Average discount-to-gross-sales ratio is {format_percent(k.discount_to_gross_sales_pct)}."
        ],
        promotion_insights=[
            f"Promotion spend represents {format_percent(k.promotion_to_gross_sales_pct)} of gross sales."
        ],
        returns_inventory_risks=[
            f"Return rate is {format_percent(k.return_rate_pct)}; {k.low_stock_sku_count} SKUs are flagged low-stock."
        ],
        opportunities=["Review the top discount bands for volume-vs-margin trade-offs (see Discount tab)."],
        management_recommendations=[
            ManagementRecommendation(
                priority="High",
                action="Review discount bands above 10% for margin erosion.",
                reason=f"Overall gross margin is {format_percent(k.gross_margin_pct)}.",
                expected_business_effect="Potential margin recovery without proportional volume loss.",
            ),
            ManagementRecommendation(
                priority="Medium",
                action="Investigate SKUs with the highest return rates.",
                reason=f"Return rate stands at {format_percent(k.return_rate_pct)} of units sold.",
                expected_business_effect="Reduced refund leakage and improved customer experience.",
            ),
        ],
        data_limitations=bundle.limitations
        + ["This analysis was generated by a local mock (USE_MOCK_AI=true), not by Claude."],
    )


def mock_mongolian_analysis(english: AIAnalysisResult) -> AIAnalysisResult:
    """A lightweight templated Mongolian rendering used only in mock mode."""
    data = english.model_dump()
    data["executive_summary"] = (
        "[MOCK ОРЧУУЛГА] " + english.executive_summary.replace("[MOCK AI]", "").strip()
        + " Энэ бол орчуулгын хуурамч горимд (USE_MOCK_AI=true) үүсгэсэн жишиг Монгол дүгнэлт юм."
    )
    data["performance_overview"] = "Гүйцэтгэлийн тойм: " + english.performance_overview
    data["data_limitations"] = english.data_limitations + [
        "Энэхүү орчуулга нь OpenAI API-г дуудалгүйгээр локал mock горимоор үүсгэгдсэн болно."
    ]
    return AIAnalysisResult(**data)
